CREATE DATABASE FATECBD1MatheusMartinsRicardoEltonEx1
GO

USE FATECBD1MatheusMartinsRicardoEltonEx1
GO

CREATE TABLE turma (	
codAtiv INT NOT NULL IDENTITY(1,1),
numAlunos INT NOT NULL,
horaAula TIME NOT NULL,
duracaoAula TIME NOT NULL,
dataInicio DATETIME NOT NULL,
dataFim DATETIME NOT NULL,
tipoAtiv VARCHAR(250) NOT NULL,
codAluno INT NOT NULL
)
GO

CREATE TABLE instrutor(
codInstrutor INT NOT NULL IDENTITY(1,1),
rg VARCHAR(25) NOT NULL UNIQUE NONCLUSTERED,
nome VARCHAR(200) NOT NULL,
dataNasc DATETIME NOT NULL,
titulacao VARCHAR NOT NULL,
tel NUMERIC NOT NULL,
cel NUMERIC NOT NULL)

GO

CREATE TABLE aluno(
codMatAluno INT NOT NULL IDENTITY(1,1),
dataMat DATETIME DEFAULT GETDATE() NOT NULL,
nome VARCHAR(200) NOT NULL,
endereco VARCHAR(250) NOT NULL,
tel NUMERIC NOT NULL,
cel NUMERIC NOT NULL,
dataNasc DATETIME NOT NULL,
altura FLOAT NOT NULL CHECK (altura >= 0),
peso FLOAT NOT NULL CHECK (peso >= 0),
rg VARCHAR(25) NOT NULL UNIQUE NONCLUSTERED,
ra VARCHAR(25) NOT NULL UNIQUE NONCLUSTERED)

GO


ALTER TABLE turma
ADD CONSTRAINT FK_aluno_codMatAluno FOREIGN KEY (codAluno)
REFERENCES aluno(codMatAluno)
GO